# Algoritmos de optimización - Trabajo Práctico<br>
Nombre y Apellidos: Gerardo Dario Sepulveda Barrera  <br>
Url: https://github.com/.../03MAIR---Algoritmos-de-Optimizacion---/tree/master/TrabajoPractico<br>
Google Colab: https://colab.research.google.com/drive/xxxxxxxxxxxxxxxx <br>
Problema:
>1. Sesiones de doblaje <br>
>2. Organizar los horarios de partidos de La Liga<br>
>3. Configuración de Tribunales

Problema 1. Organizar sesiones de doblaje(I)<br>
Se precisa coordinar el doblaje de una película. <br>
Los actores del doblaje deben coincidir en las tomas en las que sus personajes aparecen juntos en las diferentes tomas. <br>
Los actores de doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de
grabación independientemente del número de tomas que se graben. <br>
No es posible grabar más de 6 tomas por día. <br>

El objetivo es planificar las sesiones por día de manera que el gasto por los
servicios de los actores de doblaje sea el menor posible. Los datos son:<br>

Número de actores: 10<br>
Número de tomas : 30<br>
Actores/Tomas : https://bit.ly/36D8IuK
- 1 indica que el actor participa en la toma
- 0 en caso contrario

# Modelo
- ¿Como represento el espacio de soluciones?
- ¿Cual es la función objetivo?
- ¿Como implemento las restricciones?

In [117]:
#Respuesta

<img src="print_funcion.png" alt="drawing" width="500"/>

# Análisis
- ¿Que complejidad tiene el problema?. Orden de complejidad y Contabilizar el espacio de soluciones

In [115]:
# Recorremos cada fila de la tabla, y para cada fila, recorremos cada columna (actor) y vemos si el actor está en la escena.
# Si el actor está en la escena, sumamos 1 a la cantidad de escenas en las que aparece el actor.
# Si el actor no está en la escena, no hacemos nada.

# Por lo tanto, la complejidad es O(np) donde n es la cantidad de escenas y p es la cantidad de actores

# Diseño
- ¿Que técnica utilizo? ¿Por qué?

In [195]:
# Dada la dimensionalidad de los datos, utilizaré una técnica voraz para resolver el problema.
# Además, añado una poda heurística de entrada (actor con menos escenas) con la finalidad de reducir dimensiones en el espacio de solución.

# La técnica consiste en ir seleccionando el actor con menor cantidad de escenas en las que aparece.
# Luego eliminamos las escenas en las que aparece ese actor.
# De esta forma, reducimos la cantidad de escenas en las que aparece ese actor, y así sucesivamente con los demás actores.

# Importamos base de datos

In [119]:
# Librerias
import pandas as pd
import re

In [120]:
def convert_google_sheet_url(url):
    # Regular expression to match and capture the necessary part of the URL
    pattern = r'https://docs\.google\.com/spreadsheets/d/([a-zA-Z0-9-_]+)(/edit#gid=(\d+)|/edit.*)?'

    # Replace function to construct the new URL for CSV export
    # If gid is present in the URL, it includes it in the export URL, otherwise, it's omitted
    replacement = lambda m: f'https://docs.google.com/spreadsheets/d/{m.group(1)}/export?' + (f'gid={m.group(3)}&' if m.group(3) else '') + 'format=csv'

    # Replace using regex
    new_url = re.sub(pattern, replacement, url)

    return new_url

In [121]:
# Replace with your modified URL
url = 'https://docs.google.com/spreadsheets/d/1Ipn6IrbQP4ax8zOnivdBIw2lN0JISkJG4fXndYd27U0/edit#gid=0'

new_url = convert_google_sheet_url(url)

print(new_url)
# https://docs.google.com/spreadsheets/d/1mSEJtzy5L0nuIMRlY9rYdC5s899Ptu2gdMJcIalr5pg/export?gid=1606352415&format=csv

https://docs.google.com/spreadsheets/d/1Ipn6IrbQP4ax8zOnivdBIw2lN0JISkJG4fXndYd27U0/export?gid=0&format=csv

In [191]:
# Importamos el archivo
df = pd.read_csv(new_url,header=1, index_col=0)
df = df.head(30)
df = df.iloc[:,:-2]
df

        1    2    3    4    5    6    7    8    9   10
Toma
1     1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
3     0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0
4     1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0
5     0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0
6     1.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
7     1.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
8     1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
9     1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
10    1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0
11    1.0  1.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0
12    1.0  1.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0
13    1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
14    1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
15    1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
16    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0
17    1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
18    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
19    1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
20    1.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
21    0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0
22    1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
23    1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
24    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
25    1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0
26    1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
27    0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
28    1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
29    1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0
30    1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0

In [192]:
# crea una funcion que calcula el maximo de cada columna y retorna la suma de los maximos
def maximo(df):
    # agrega una fila con el maximo de cada columna
    df.loc['max'] = df.max()
    # calcula la suma de las columnas 1,2,3,4,5,6,7,8,9 y 10 donde se encuentran los maximos
    df['suma_maximos'] = df.iloc[:,0:10].sum(axis=1)
    # retorna columna suma_maximos en index max
    return df['suma_maximos']['max']

In [216]:
# crea una funcion que calcula el minimo de cada columna y retorna la suma de los minimos
def greedy_optimize(_data):

    days = []
    data = _data.copy()
    while len(data) > 0:
        costs_by_actor = data.sum()
        # Toma el actor con menor cantidad de escenas
        actor = costs_by_actor.idxmin()
        # Toma las escenas en las que aparece el actor
        scenes = data[data[actor] > 0].index
        # Obtiene los actores en las escenas del actor con menor cantidad de escenas
        actors = (data.loc[scenes].sum() > 0).astype(int)
        # Toma las escenas en las que aparecen los actores seleccionados
        scenes = ((data - actors) <= 0).all(axis=1)
        # Obtiene el indice de las primeras seis escenas
        scenes = scenes[scenes].index[:6]
        days.append(scenes)
        
        # Quita las escenas consideradas
        data = data.drop(scenes)
        data = data.drop(actor, axis=1)
        
    # Elimina los dias vacios
    days = [day for day in days if len(day) > 0]
    return days

In [217]:
from termcolor import colored

days = greedy_optimize(df)
maximos = []
# para cada elemento de days, imprime el numero de dia y los actores en el dia
for i, day in enumerate(days):
    print(colored(f'Day {i+1}','red', attrs=['bold']))
    # imprime los actores con max igual a 1
    print(f'Actors: {", ".join(df.loc[day].max()[df.loc[day].max() == 1].index)}')
    # imprime las escenas en el dia
    print(f'Scenes: {", ".join(day)}')
    # imprime el costo del dia
    maximos.append(maximo(df.loc[day]))
    #print(f'Cost: {df.loc[day].sum().sum()}')
    print(f'Cost: {maximo(df.loc[day])}')
    # imprime una linea en blanco
    #print()
    

print("")
print(colored(f"Total cost: {sum(maximos)}", attrs=['bold']))

Day 1
Actors: 1, 2, 3, 6, 9
Scenes: 8, 10, 14, 17, 18, 19
Cost: 5.0
Day 2
Actors: 1, 2, 4, 10
Scenes: 9, 16, 25, 28, 30
Cost: 4.0
Day 3
Actors: 1, 2, 5, 7, 8
Scenes: 3, 4, 15
Cost: 5.0
Day 4
Actors: 1, 2, 3, 4, 5, 8
Scenes: 1, 2, 5, 6, 7, 11
Cost: 6.0
Day 5
Actors: 1, 2, 3, 4, 6, 8
Scenes: 12, 21, 22, 23, 24
Cost: 6.0
Day 6
Actors: 1, 5, 6
Scenes: 29
Cost: 3.0
Day 7
Actors: 1, 3, 4, 5, 9
Scenes: 13, 20, 26, 27
Cost: 5.0

Total cost: 34.0